### PR TITLE
[JENKINS-55944] Add typical .gitignore file and remove committed target dir

### PR DESCRIPTION
**Pull request by batmat**
Found JAXB related occurrences while working on [JENKINS-55944](https://issues.jenkins-ci.org/browse/JENKINS-55944), so filed this PR for cleaning up.

Cheers!

cc @jenkinsci/java11-support

### CODE REVIEW

**Review by MRamonLeon — APPROVED** [review]
:clap: :clap: :clap: :clap: :clap:

**Review by alecharp — APPROVED** [review]
:clap:

**Comment by batmat** [comment]
I suspect this plugin might be orphaned, given also the status of (Atlassian's, I assume) Stride IIRC.

**Comment by batmat** [comment]
@anjal-pachat can you possibly merge this? Thanks

**Comment by timja** [comment]
😢 this is spamming my search results

**Comment by batmat** [comment]
Going to propose the archival of this repo

Makes no sense to keep this given the software it's connecting got EoLed in Feb 2019.

https://en.wikipedia.org/wiki/Stride_(software)

**Comment by timja** [comment]
> Going to propose the archival of this repo
> 
> Makes no sense to keep this given the software it's connecting got EoLed in Feb 2019.
> 
> [en.wikipedia.org/wiki/Stride_(software)](https://en.wikipedia.org/wiki/Stride_(software))

Archiving doesn't remove from search results so I still recommend merging this

**Pull request merged**
